import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { LeftPanel } from "@/components/widgets/left-panel";
import { IWithChildren } from "@/types";
import './layout.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "A.V. Petrov CV",
  description: "Generated by create next app", // TODO: edit
};

export default function RootLayout({ children }: IWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          <LeftPanel />
          <div className='container__content'>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
