import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { ILeftPanelProps, LeftPanel } from "@/components/widgets/left-panel";
import { IWithParams } from "@/types";
import './layout.scss'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "A.V. Petrov CV",
  description: "Generated by create next app", // TODO: edit
};

export interface IRootLayoutProps extends IWithParams<ILeftPanelProps> {}

export default function RootLayout({ children, params }: IRootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
