import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import './left-panel-layout.scss';
import { ILeftPanelProps, LeftPanel } from "@/components/widgets/left-panel";
import { IMenuProps } from "@/components/features/menu/menu";
import { IWithParams } from "@/types";
import { PageNames } from "@/constants";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface IRootLayoutProps extends IWithParams<ILeftPanelProps> { }

export const LeftPanelLayout = ({ children, params }: IRootLayoutProps) => {
  return (
    <>
      <LeftPanel page={params.page} /> {/* TODO Слишком длинный спуск? */}
      <div className="content">
        {children}
      </div>
    </>
  );
}
